# Generated by Django 4.2.7 on 2023-11-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbs_app", "0004_remove_book_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="author",
            name="key",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="languages",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="publishers",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
