# Generated by Django 4.2.7 on 2023-11-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbs_app", "0005_book_isbn_alter_author_key_alter_author_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="languages",
        ),
    ]
