# Generated by Django 3.0.5 on 2023-12-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs_app', '0006_remove_book_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(default=0)),
                ('description', models.TextField(default='')),
                ('publisher_year', models.IntegerField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'library_databaseCollection',
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
